#spring:
#  zipkin:
#    baseUrl: http://localhost:9411/  
#    enabled: true 

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
  healthcheck:
      enabled: true
  lease:
      duration: 5

      