#spring:
#  zipkin:
#    baseUrl: http://localhost:9411/  
#    enabled: true 

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://whitewalkersdiscoveryservice:8761/eureka/

      