whitewalkers-config-service:
  hostname: "whitewalkersconfigserver"
  image: whitewalkers-config-service:v1
  ports:
       - "8888:8888"
       
whitewalkers-discovery-service:
  hostname: "whitewalkersdiscoveryservice"
  image: whitewalkers-discovery-service:v1
  ports:
     - "8889:8889"
  links:
     - "whitewalkers-config-service:whitewalkersconfigserver"
  environment:
    MEM_ARGS: "-Xmx128m"
    SERVER_PORT: "8889"
    CONFIGSERVER_URI: "http://whitewalkersconfigserver:8888"
    CONFIGSERVER_HOST: "whitewalkersconfigserver"
    CONFIGSERVER_PORT: "8888"
    
whitewalkers-query-service:
  hostname: "whitewalkersqueryservice"
  image: whitewalkers-query-service:v1
  ports:
     - "9091:9091"
  links:
     - "whitewalkers-config-service:whitewalkersconfigserver"
     - "whitewalkers-discovery-service:whitewalkersdiscoveryservice"
     - "whitewalkers-tweet-database:whitewalkerstweetdatabase"
  environment:
    MEM_ARGS: "-Xmx128m"
    SERVER_PORT: "9091"
    CONFIGSERVER_URI: "http://whitewalkersconfigserver:8888"
    CONFIGSERVER_HOST: "whitewalkersconfigserver"
    CONFIGSERVER_PORT: "8888"
    DISCOVERYSERVER_URI: "http://whitewalkersdiscoveryservice:8889/eureka"
    DISCOVERYSERVER_HOST: "whitewalkersdiscoveryservice"
    DISCOVERYSERVER_PORT: "8889"
    DBSERVER_HOST: "whitewalkerstweetdatabase"
    DBSERVER_PORT: "27017"
    
whitewalkers-tweet-service:
  hostname: "whitewalkerstweetservice"
  image: whitewalkers-tweet-service:v1
  ports:
     - "9090:9090"
  links:
     - "whitewalkers-config-service:whitewalkersconfigserver"
     - "whitewalkers-discovery-service:whitewalkersdiscoveryservice"
     - "whitewalkers-tweet-database:whitewalkerstweetdatabase"
  environment:
    MEM_ARGS: "-Xmx128m"
    SERVER_PORT: "9090"
    CONFIGSERVER_URI: "http://whitewalkersconfigserver:8888"
    CONFIGSERVER_HOST: "whitewalkersconfigserver"
    CONFIGSERVER_PORT: "8888"
    DISCOVERYSERVER_URI: "http://whitewalkersdiscoveryservice:8889/eureka"
    DISCOVERYSERVER_HOST: "whitewalkersdiscoveryservice"
    DISCOVERYSERVER_PORT: "8889"
    DBSERVER_HOST: "whitewalkerstweetdatabase"
    DBSERVER_PORT: "27017"
    
whitewalkers-twitter-stream-service:
  hostname: "whitewalkerstwitterstreamservice"
  image: whitewalkers-twitter-stream-service:v1
  ports:
     - "9092:9092"
  links:
     - "whitewalkers-config-service:whitewalkersconfigserver"
     - "whitewalkers-discovery-service:whitewalkersdiscoveryservice"
     - "whitewalkers-tweet-database:whitewalkerstweetdatabase"
  environment:
    MEM_ARGS: "-Xmx128m"
    SERVER_PORT: "9092"
    CONFIGSERVER_URI: "http://whitewalkersconfigserver:8888"
    CONFIGSERVER_HOST: "whitewalkersconfigserver"
    CONFIGSERVER_PORT: "8888"
    DISCOVERYSERVER_URI: "http://whitewalkersdiscoveryservice:8889/eureka"
    DISCOVERYSERVER_HOST: "whitewalkersdiscoveryservice"
    DISCOVERYSERVER_PORT: "8889"
    DBSERVER_HOST: "whitewalkerstweetdatabase"
    DBSERVER_PORT: "27017"
    
whitewalkers-proxy-service:
  hostname: "whitewalkersproxyservice"
  image: whitewalkers-proxy-service:v1
  ports:
     - "9999:9999"
  links:
     - "whitewalkers-config-service:whitewalkersconfigserver"
     - "whitewalkers-discovery-service:whitewalkersdiscoveryservice"
  environment:
    MEM_ARGS: "-Xmx128m"
    SERVER_PORT: "9999"
    CONFIGSERVER_URI: "http://whitewalkersconfigserver:8888"
    CONFIGSERVER_HOST: "whitewalkersconfigserver"
    CONFIGSERVER_PORT: "8888"
    DISCOVERYSERVER_URI: "http://whitewalkersdiscoveryservice:8889/eureka"
    DISCOVERYSERVER_HOST: "whitewalkersdiscoveryservice"
    DISCOVERYSERVER_PORT: "8889"
    
whitewalkers-tweet-database:
  hostname: "whitewalkerstweetdatabase"
  image: mongo:latest
  ports:
     - "27017:27017"
  environment:
     - MONGO_DB = "twitter"
     - MONGO_PORT = "27017"
     
       
       